// Generated by CoffeeScript 1.6.3
(function() {
  var apihost, request, version, xhr;

  xhr = require('request');

  apihost = 'http://mdash.ru/api.{version}.php';

  version = 'v1';

  request = function(params, fn) {
    var host;
    if (fn == null) {
      fn = function() {};
    }
    host = apihost.replace('{version}', version);
    xhr.post(host, {
      form: params
    }, function(error, request, body) {
      var data;
      try {
        body = JSON.parse(body);
        if (body.status != null) {
          error = body.status;
        }
        data = body.result != null ? body.result : null;
      } catch (_error) {
        error = _error;
        data = null;
        error = 'Unable to parse JSON response from mdash.ru';
      }
      fn(error, data);
    });
  };

  module.exports = {
    apply: function(text, fn) {
      var params;
      params = {
        text: text
      };
      request(params, fn);
    }
  };

}).call(this);
